import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import Brand from "./components/Brand";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const DatetimeDisplayClient = dynamic(
  () => import("./components/DatetimeDisplay"),
  { ssr: false }
);

export const metadata: Metadata = {
  title: "News Scrap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Brand />
        <DatetimeDisplayClient />
        {children}
      </body>
    </html>
  );
}
